/**************************************************************************
    Notice: 
        1.  请不要直接include本文件！！！
        2.  请include "gpioapp.h来访问相应的枚举值以及名称对应关系
        3.  这个文件用来在gpioapp.h中定义OUTPUT_NAME
        4.  枚举名字和值的对应关系定义在gpio_common.cpp:_sGpioOutputEnumNameMap中
****************************************************************************/

DEFINE_GPIO_ITEM(MIO_PS_WD) //U31:复位芯片喂狗信号
DEFINE_GPIO_ITEM(MIO_PS_ENET_RESET)
DEFINE_GPIO_ITEM(MIO_PS_USB_RESET)
DEFINE_GPIO_ITEM(MIO_PS_USB_CS)
DEFINE_GPIO_ITEM(MIO_EMMC0_SD0_RSTN)
DEFINE_GPIO_ITEM(MIO_V3_1)
DEFINE_GPIO_ITEM(MIO_V2_1)
DEFINE_GPIO_ITEM(MIO_V1_1)
DEFINE_GPIO_ITEM(MIO_V3_2)
DEFINE_GPIO_ITEM(MIO_V2_2)
DEFINE_GPIO_ITEM(MIO_V1_2)
DEFINE_GPIO_ITEM(MIO_GPIO0_DISPLAY)
DEFINE_GPIO_ITEM(MIO_GPIO1_DISPLAY)
DEFINE_GPIO_ITEM(MIO_USB_5V_EN)
DEFINE_GPIO_ITEM(MIO_EN_1)
DEFINE_GPIO_ITEM(MIO_EN_2)
DEFINE_GPIO_ITEM(MIO_ETH_VCC_1V2_EN)
DEFINE_GPIO_ITEM(MIO_VDD_3V3_EN)
DEFINE_GPIO_ITEM(MIO_VDD_1V8_EN)
DEFINE_GPIO_ITEM(MIO_VCC_5V_EN)
DEFINE_GPIO_ITEM(EMIO_SYS_LED0)
DEFINE_GPIO_ITEM(EMIO_SYS_LED1)
DEFINE_GPIO_ITEM(EMIO_SYS_LED2)
DEFINE_GPIO_ITEM(EMIO_SYS_LED3)

DEFINE_GPIO_ITEM(EMIO_FAN_EN)   //输出高电平风扇供电
DEFINE_GPIO_ITEM(EMIO_BUZZER_EN)   //输出高电平蜂鸣器供电电源输出
DEFINE_GPIO_ITEM(EMIO_VBRATOR_EN)   //高电平马达电源输出

DEFINE_GPIO_ITEM(EMIO_SWITCH_OE2)   //高电平使能I2C电平转换和温度传感器中断输出的电平转换
DEFINE_GPIO_ITEM(EMIO_AVCC_ADJ_EN)   //输出高电平使能运放的电源输出
DEFINE_GPIO_ITEM(EMIO_DAC_3V3_EN)   //高电平输出DAC工作电压
DEFINE_GPIO_ITEM(EMIO_G_CLK_EN)   //高电平使能时钟缓冲输出
DEFINE_GPIO_ITEM(EMIO_AVCC_5V_EN)   //高电平使能运放5V工作电压输出
DEFINE_GPIO_ITEM(EMIO_AVCC_1V8_EN)   //高电平使能ADC1.8V工作电压输出
DEFINE_GPIO_ITEM(EMIO_ADC_RESET)   //低电平复位ADC芯片
DEFINE_GPIO_ITEM(EMIO_ADC_SEN)   //低电平使能ADC通讯功能
DEFINE_GPIO_ITEM(EMIO_SWITCH_5V_EN)   //高电平使能9361 5V输出
DEFINE_GPIO_ITEM(EMIO_ADC_PDN)   //低电平给ADC开启供电
DEFINE_GPIO_ITEM(EMIO_SWITCH_12V_EN)   //高电平使能开关滤波器12V输出
DEFINE_GPIO_ITEM(EMIO_L_CTRL_D0)
DEFINE_GPIO_ITEM(EMIO_L_CTRL_D1)
DEFINE_GPIO_ITEM(EMIO_L_CTRL_D2)
DEFINE_GPIO_ITEM(EMIO_L_CTRL_D3)
DEFINE_GPIO_ITEM(EMIO_L_CTRL_D4)
DEFINE_GPIO_ITEM(EMIO_L_CTRL_D5)
DEFINE_GPIO_ITEM(EMIO_L_CTRL_D6)
DEFINE_GPIO_ITEM(EMIO_SWITCH_OE0)   //控制数控衰减器衰减大小数字量（D0-D3）电平转换的控制开关，高电平开启电平转换
DEFINE_GPIO_ITEM(EMIO_SWITCH_OE1)   //控制数控衰减器衰减大小数字量（D4-D6）电平转换的控制开关，高电平开启电平转换
DEFINE_GPIO_ITEM(EMIO_CTRL_IN3)   //
DEFINE_GPIO_ITEM(EMIO_CTRL_IN2)   //
DEFINE_GPIO_ITEM(EMIO_CTRL_IN1)   //
DEFINE_GPIO_ITEM(EMIO_CTRL_IN0)   //
DEFINE_GPIO_ITEM(EMIO_ACC_CS)   //电子罗盘I2C/SPI mode selection1: SPI idle mode / I2C communication enabled;0: SPI communication mode / I2C disabled
DEFINE_GPIO_ITEM(EMIO_PROG_SET1)   //程序运行状态指示灯控制1
DEFINE_GPIO_ITEM(EMIO_PROG_SET2)   //程序运行状态指示灯控制2
DEFINE_GPIO_ITEM(EMIO_PROG_SET3)   //程序运行状态指示灯控制3
DEFINE_GPIO_ITEM(EMIO_PROG_SET4)   //程序运行状态指示灯控制4
DEFINE_GPIO_ITEM(EMIO_GPS_RESET)   //GPS_RESET
DEFINE_GPIO_ITEM(EMIO_GPS_FORCE_ON)   //GPS_FORCE_ON
DEFINE_GPIO_ITEM(EMIO_SWITCH_OE5)   //上面三个IO口电平转换使能控制，高电平开启电平转换
DEFINE_GPIO_ITEM(EMIO_SWITCH_OE4)   //下面四个IO口电平转换使能控制，高电平开启电平转换
DEFINE_GPIO_ITEM(EMIO_SWITCH_OE7)   //下面四个IO口电平转换使能控制，高电平开启电平转换
DEFINE_GPIO_ITEM(EMIO_SWITCH_OE6)   //下面两个IO口电平转换使能控制，高电平开启电平转换
DEFINE_GPIO_ITEM(EMIO_WIFI_WAKEUP_OUT)   //
DEFINE_GPIO_ITEM(EMIO_WIFI_RST)   //WIFI_RST
DEFINE_GPIO_ITEM(EMIO_GYRO_CS)
DEFINE_GPIO_ITEM(EMIO_GYRO_EN)
DEFINE_GPIO_ITEM(EMIO_WIFI_WAKEUP_IN_OUT)
DEFINE_GPIO_ITEM(EMIO_DX_CTRL_OUT0) //Value = 67
DEFINE_GPIO_ITEM(EMIO_DX_CTRL_OUT1)
DEFINE_GPIO_ITEM(EMIO_CHANNEL_CTRLA_0)
DEFINE_GPIO_ITEM(EMIO_RF_CTLA_0)  // 70
DEFINE_GPIO_ITEM(EMIO_RF_CTLB_0)
DEFINE_GPIO_ITEM(EMIO_RF_CTLA_1)
DEFINE_GPIO_ITEM(EMIO_RF_CTLB_1)
DEFINE_GPIO_ITEM(EMIO_RF_CTLA_2)
DEFINE_GPIO_ITEM(EMIO_RF_CTLB_2)
DEFINE_GPIO_ITEM(EMIO_RF_CTLA_3)
DEFINE_GPIO_ITEM(EMIO_RF_CTLB_3)
DEFINE_GPIO_ITEM(EMIO_RF_GPIO_0)
DEFINE_GPIO_ITEM(EMIO_RF_GPIO_1)
DEFINE_GPIO_ITEM(EMIO_RF_GPIO_2)  // 80
DEFINE_GPIO_ITEM(EMIO_RF_GPIO_3)
DEFINE_GPIO_ITEM(EMIO_RF_GPIO_4)  // 82
DEFINE_GPIO_ITEM(EMIO_RF_GPIO_5)
DEFINE_GPIO_ITEM(EMIO_RF_GPIO_6)
DEFINE_GPIO_ITEM(EMIO_RF_GPIO_7)

/***For T3 board) begin ******************/
DEFINE_GPIO_ITEM(EMIO_RN440_3V3_EN) // RN440 电源使能控制 1：使能 0：不使能（缺省）
DEFINE_GPIO_ITEM(EMIO_RG450_3V3_EN) // RG450 电源使能控制 1：使能 0：不使能（缺省）
DEFINE_GPIO_ITEM(EMIO_LT3045_EN) // RN440 射频电路 LDO_5V 电源使能控制(RSV_3V3_IO3 on T2) 1：使能 0：不使能（缺省）
DEFINE_GPIO_ITEM(EMIO_ADL5904_RST) // ADL5904 复位控制 1：复位（缺省） 0：正常工作
DEFINE_GPIO_ITEM(EMIO_PE42442_V1) // 90 PE42442 射频通道切换控制信号 V1(RSV_3V3_IO0 on T2) 
DEFINE_GPIO_ITEM(EMIO_PE42442_V2) // 91 PE42442 射频通道切换控制信号 V2(RSV_3V3_IO6 on T2) 
DEFINE_GPIO_ITEM(EMIO_PE42442_V3) // 92 PE42442 射频通道切换控制信号 V3(RSV_3V3_IO7 on T2) 
DEFINE_GPIO_ITEM(MIO_PS_UART1_TX) // RN440 蓝牙串口，SOC 发送V3(PS_UART1_TX/MIO_VCC_5V_EN on T2) 
DEFINE_GPIO_ITEM(EMIO_PL_UART1_TX) // MCU通信串口，SOC 发送V3(PL_UART1_TX on T2) 
DEFINE_GPIO_ITEM(EMIO_ANT_CTL_5V_EN) //天线5V使能控制(T2包含但未控制)
DEFINE_GPIO_ITEM(EMIO_ANT_CTL3_OE) // ANT_CTL3的输出使能控制 1：不使能 ANT_CTL3 输出（缺省） 0：使能 ANT_CTL3 输出
DEFINE_GPIO_ITEM(EMIO_ANT_CTL3) // 车载天线控制输出信号3
DEFINE_GPIO_ITEM(EMIO_ANT_CTL4) // 车载天线控制输出信号4
DEFINE_GPIO_ITEM(EMIO_ANT_CTL5) // 车载天线控制输出信号5

DEFINE_GPIO_ITEM(EMIO_RN440_H_WK_WL)
DEFINE_GPIO_ITEM(EMIO_RN440_H_WK_BT)
DEFINE_GPIO_ITEM(EMIO_RN440_WL_DIS)
DEFINE_GPIO_ITEM(EMIO_RN440_BT_DIS)
DEFINE_GPIO_ITEM(EMIO_RSV_3V3_IO3)

DEFINE_GPIO_ITEM(EMIO_RG450_BT_EN)
DEFINE_GPIO_ITEM(EMIO_RG450_WL_EN)

DEFINE_GPIO_ITEM(MIO_SWITCH_CHANNEL_0)
DEFINE_GPIO_ITEM(MIO_SWITCH_CHANNEL_1)
DEFINE_GPIO_ITEM(MIO_SWITCH_CHANNEL_2)
DEFINE_GPIO_ITEM(MIO_SWITCH_CHANNEL_3)
DEFINE_GPIO_ITEM(EMIO_SWITCH_CHANNEL_4)
DEFINE_GPIO_ITEM(MIO_SWITCH_CHANNEL_5)

/***For T3 board) end ******************/

DEFINE_GPIO_ITEM(OUTPUT_NAME_MAX)
