#include "input.h"
#include "../../../srv/log/log.h"

const  INPUT_ARG InputArg[OUTPUT_NAME_MAX] =
{
		[MIO_MUTE_SWITCH]		= { ENABLE, MIO, GPIO_DEVICE_ID, 0, 37},
		[MIO_SWITCH_MODE0]		= { ENABLE, MIO, GPIO_DEVICE_ID, 0, 38},
		[MIO_SWITCH_MODE1]		= { ENABLE, MIO, GPIO_DEVICE_ID, 0, 40},
		[MIO_SWITCH_MODE2]		= { ENABLE, MIO, GPIO_DEVICE_ID, 0, 43},
		[MIO_SWITCH_MODE3]		= { ENABLE, MIO, GPIO_DEVICE_ID, 0, 8},

		[EMIO_CONFIG_SW]         = { ENABLE, EMIO, GPIO_DEVICE_ID, 0, EMIO_OFFSET + 43},
		[EMIO_GPS_SW]            = { ENABLE, EMIO, GPIO_DEVICE_ID, 0, EMIO_OFFSET + 61},
		[EMIO_TRIGGER]           = { ENABLE, EMIO, GPIO_DEVICE_ID, 0, EMIO_OFFSET + 67},
		[EMIO_VCC0_21V_OUT_INT]  = { ENABLE, EMIO, GPIO_DEVICE_ID, 0, EMIO_OFFSET + 62},
		[EMIO_FAN_SENSOR]        = { ENABLE, EMIO, GPIO_DEVICE_ID, 0, EMIO_OFFSET + 54},
		[EMIO_GYRO_INT2_DRDY]    = { ENABLE, EMIO, GPIO_DEVICE_ID, 0, EMIO_OFFSET + 11},
		[EMIO_GYRO_INT1]         = { ENABLE, EMIO, GPIO_DEVICE_ID, 0, EMIO_OFFSET + 10},
		[EMIO_ACC_MAGINT]        = { ENABLE, EMIO, GPIO_DEVICE_ID, 0, EMIO_OFFSET + 23},
//		[EMIO_ACC_INT2_XL]       = { ENABLE, EMIO, GPIO_DEVICE_ID, 0, EMIO_OFFSET + 22},
//		[EMIO_ACC_INT1_XL]       = { ENABLE, EMIO, GPIO_DEVICE_ID, 0, EMIO_OFFSET + 21},
//		[EMIO_WIFI_NET_STATUS]   = { ENABLE, EMIO, GPIO_DEVICE_ID, 0, EMIO_OFFSET + 66},
//		[EMIO_WIFI_WAKEUP_IN]    = { DISABLE, EMIO, GPIO_DEVICE_ID, 0, EMIO_OFFSET + 64},
//		[EMIO_WIFI_RX1]          = { ENABLE, EMIO, GPIO_DEVICE_ID, 0, EMIO_OFFSET + 68},
		[EMIO_CTRL_OUT0]         = { ENABLE, EMIO, GPIO_DEVICE_ID, 0, EMIO_OFFSET + 44},
		[EMIO_CTRL_OUT1]         = { ENABLE, EMIO, GPIO_DEVICE_ID, 0, EMIO_OFFSET + 45},
		[EMIO_CTRL_OUT2]         = { ENABLE, EMIO, GPIO_DEVICE_ID, 0, EMIO_OFFSET + 46},
//		[EMIO_CTRL_OUT3]         = { ENABLE, EMIO, GPIO_DEVICE_ID, 0, EMIO_OFFSET + 47},
//		[EMIO_CTRL_OUT4]         = { ENABLE, EMIO, GPIO_DEVICE_ID, 0, EMIO_OFFSET + 48},
//		[EMIO_CTRL_OUT5]         = { ENABLE, EMIO, GPIO_DEVICE_ID, 0, EMIO_OFFSET + 49},
		[EMIO_VCC28V_PG_1V8]     = { ENABLE, EMIO, GPIO_DEVICE_ID, 0, EMIO_OFFSET + 35},
		[EMIO_VCC32V_PG_1V8]     = { ENABLE, EMIO, GPIO_DEVICE_ID, 0, EMIO_OFFSET + 34},

};


int32_t InputInit(void)
{
	return 0;
}

int32_t InputUninit(void)
{
	return 0;
}

uint8_t Input_GetValue(INPUT_NAME name)
{
	return 0;
}
